### ISSUE TITLE
affixpythoninterface.py seems to be unable to overload network functionalities multiple times.

### ISSUE THREAD

**Issue by monzum** [SeattleTestbed/affix#16]
affixpythoninterface.py is an interface that allows user to use the AFFIX framework from python with ease. affixpythoninterface by default overwrites the Repy network API with functions that use AFFIX with the default AFFIX string of CoordinationAffix. However setting a new string does not seem to update the new network calls to use a new AFFIX stack built from the new string.

**Comment by aaaaalbert** [comment]
Closing as WONTFIX as the previous Python interface isn't supported anymore.
