### ISSUE TITLE
Directory structure in github

### ISSUE THREAD

**Issue by ffund** [SeattleTestbed/affix#29]
Currently there are conflicting versions of certain files in different directories in the github repository (e.g., from Affix repo and from Seattle libraries). This should really be cleaned up. At the very least, there should be a README that describes the order of precedence in which to copy the various files to a new directory. 

Perhaps - since all files need to be in the same directory or Python path to run, anyways - we should consider a flat directory structure in the github repository.

**Comment by aaaaalbert** [comment]
Essentially fixed now that all Seattle repos use build scripts, see [the common build instructions](https://seattle.poly.edu/wiki/BuildInstructions). For useful sub-parts like the TCP relay, the corresponding subdirs have separate READMEs and build scripts as well.
