### ISSUE TITLE
Popping an Affix from the stack may put RepyNetworkAPIWrapper at the bottom of the stack.

### ISSUE THREAD

**Issue by monzum** [SeattleTestbed/affix#36]
When Affixes are popped from the stack, the RepyNetworkAPIWrapper might be placed into the bottom of the stack when we have popped all the Affixes. This may cause a problem when attempting to peek(), as RepyNetworkAPIWrapper does not have the attribute peek().

One option would be to raise an error once we have reached the bottom of the stack. A second option would be to add in the attributes peek(), push() and pop() into the RepyNetworkAPIWrapper. Thoughts?

**Comment by aaaaalbert** [comment]
Fixed in d452df0ad09c2694ebca8e2b8b0d870474dedf5e in the Repy Network API wrapper.
